[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zero = "2h6xUH6T6695e8Ebvp2TpmbLeKdLd2tu6MriZq8c5RMu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
