[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_associate_token = "CNjPekVCxSLbdDX7ykECFPKcbvRehh8yj8gfaNjjMPF7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
